# Generated by Django 4.2.1 on 2023-08-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_alter_seller_seller_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
