# Generated by Django 4.2.1 on 2023-08-23 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_alter_seller_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellerToken',
        ),
    ]
